name: flutter_pcsc_windows
description: Windows implementation of the flutter_pcsc plugin for using PCSC smartcard readers.
version: 0.0.3
repository: https://github.com/joshuajylin/flutter_pcsc.git
publish_to: none

environment:
  sdk: '>= 3.0.1'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.2
  flutter_pcsc_platform_interface:
    path: ../flutter_pcsc_platform_interface
    #git:
    #  url: https://github.com/joshuajylin/flutter_pcsc.git
    #  path: 'flutter_pcsc_platform_interface'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  ffigen: ^8.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    implements: flutter_pcsc
    platforms:
      windows:
        pluginClass: none
        dartPluginClass: PcscWindows

ffigen:
  name: NativeLibraryWinscard
  description: Bindings to winscard.dll
  output: 'generated_bindings.dart'
  headers:
    entry-points:
      - 'headers/winscard.h'
    include-directives:
      - '**winscard.h'
