name: flutter_pcsc
description: Flutter plugin to access PCSC readers on Linux/Windows/MacOS
version: 0.0.4
repository: https://github.com/joshuajylin/flutter_pcsc.git
publish_to: none
environment:
  sdk: '>= 3.0.1'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_pcsc_linux:
    path: ../flutter_pcsc_linux
    #git:
    #  url: https://github.com/joshuajylin/flutter_pcsc.git
    #  path: 'flutter_pcsc_linux'
  flutter_pcsc_macos:
    path: ../flutter_pcsc_macos
    #git:
    #  url: https://github.com/joshuajylin/flutter_pcsc.git
    #  path: 'flutter_pcsc_macos'
  #flutter_pcsc_platform_interface:
  #  git:
  #    url: https://github.com/joshuajylin/flutter_pcsc.git
  #    path: 'flutter_pcsc_platform_interface'
  flutter_pcsc_windows:
    path: ../flutter_pcsc_windows
    #git:
    #  url: https://github.com/joshuajylin/flutter_pcsc.git
    #  path: 'flutter_pcsc_windows'
  ffi: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  plugin_platform_interface: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      linux:
        default_package: flutter_pcsc_linux
      macos:
        default_package: flutter_pcsc_macos
      windows:
        default_package: flutter_pcsc_windows
