name: flutter_pcsc_example
description: Demonstrates how to use the flutter_pcsc plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>= 3.0.1'

dependencies:
  flutter:
    sdk: flutter

  flutter_pcsc:
    git: 
      url: 'https://github.com/joshuajylin/flutter_pcsc.git'
      path: 'flutter_pcsc'

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
